Develop
timurlan05/Sprint_2 pull request #8
Opened 2023-06-14 07:54 UTC by timurlan05

На проверку

2023-06-16 11:45 UTC, timurlan05 commented
Добавил тест на метод get_list_of_favorites_books.

2023-06-16 13:03 UTC, kadirovgm requested changes

2023-06-16 14:47 UTC, timurlan05 commented on tests.py
> +        assert collector.favorites == []
Исправил

2023-06-17 13:33 UTC, kadirovgm approved these changes

2023-06-17 13:33 UTC, kadirovgm commented on tests.py
> +        assert "Book 1" not in collector.get_list_of_favorites_books()
отлично!

2023-06-17 13:33 UTC, kadirovgm commented on tests.py
> +        assert collector.get_list_of_favorites_books() == []
супер

2023-06-17 13:33 UTC, kadirovgm commented on tests.py
> +        assert all(book in collector.get_books_with_specific_rating(5) for book in ["Book 1", "Book 3"])
в целом правильно конечно, но можно было так и не усложнять, но принимаю :)

2023-06-17 13:33 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize("invalid_rating", [-1, 0, 11, 12])
отлично! но кажется 12 можно было и не проверять, тк 11 входит в экивалентный класс

2023-06-19 07:49 UTC, merged